pub mod fruits_into_baskets;
pub mod longest_subarray_with_ones_replacement;
pub mod longest_substring_k_distinct;
pub mod longest_substring_same_letters_replacement;
pub mod max_sum_subarray_size_k;
pub mod smallest_subarray_with_greater_sum;
